### ISSUE TITLE
Throws an error upon install

### ISSUE THREAD

**Issue by jabranham** [kjhealy/emacs-starter-kit#20]
I read your article "Choosing workflow apps" and was interested enough to look into Emacs. However, when I installed the emacs starter kit, it throws the following issue:

File error: Cannot open load file, no such file or directory, ob-shell

If it makes a difference, I am running Linux (Ubuntu).

**Comment by jabranham** [comment]
Also, (and I'm not sure if this is an error or expected behavior), but when I evaluate a command from a *.R script with C-c C-c, the script becomes read-only in emacs.

**Comment by jzelner** [comment]
I actually just ran into this issue on a clean install of Emacs 24.5-1 for Mac. The latest version of Org should be bundled in with this Emacs binary, so I'm not sure what the issue is? Any help would be greatly appreciated, because otherwise the starter kit is really amazing!

**Comment by emraher** [comment]
In "starter-kit-org.org" file change line 105. Instead of "shell" write "sh". This fixed my problem.

**Comment by NahomKidane** [comment]
@emraher  Thanks that worked for me.

**Comment by DanyaLagos** [comment]
This worked for me too. Thanks!

**Comment by henningninneh** [comment]
had the same problem. thanks for the fix.
