### ISSUE TITLE
Warning (bytecomp): ‘flet’ is an obsolete macro (as of 24.3); use either ‘cl-flet’ or ‘cl-letf’.

### ISSUE THREAD

**Issue by rbirkelbach** [kjhealy/emacs-starter-kit#21]
Hi,

I'm using emacs 25 on GNU/Linux Ubuntu 16.04. After installation of the emacs-starter-kit, I get the following warning:

`Warning (bytecomp): ‘flet’ is an obsolete macro (as of 24.3); use either ‘cl-flet’ or ‘cl-letf’``

How should I proceed to remove the warning?

Thanks in advance,
Robert

**Comment by cmbosancianu** [comment]
Hi Robert,

I got the same warning after updating to Emacs 25, and I managed to solve it by modifying the starter-kit-aspell.el file. Line 18 contains a call to "flet"; changing it to "cl-flet" removed the warning for me.

Manuel
