### ISSUE TITLE
Package 'magit-' is unavailable

### ISSUE THREAD

**Issue by apc** [kjhealy/emacs-starter-kit#23]
New to emacs. Tried setting things up from scratch using this starter kit but I get an error message when starting emacs: `error: Package ‘magit-’ is unavailable`. Tried `M-x refresh-package-contents` and restarted to no avail. If I do `M-x list-packages` I see a list of packages starting with `magit-` (but no `magit`) that are marked as incompatiible. 

After deleting the starter kit, I started with a clean `init.el` file and nothing else in my `~/.emacs.d`, pointed to MELPA and managed to get `magit` installed without a problem. 

I'm on OSX, using GNU Emacs v. 25.2.1, Git v. 2.12.1.

**Comment by kjhealy** [comment]
Thanks for the report. An outdated instruction in `starter-kit.org` was filtering out a few MELPA packages, including magit. This was a hangover from around magit 2.4 or so, I think, when things weren't working properly with the development version. It should have been removed earlier. I just pushed a fix that should sort it out.

**Comment by apc** [comment]
I think there's still a similar issue with the pushed changes. The problem now has to do with the `python` package (which is being called on line 15 of `starter-kit-python.org` ). I searched both the MELPA and ELPA lists and couldn't find a package with that name.
